---
- hosts: db
  sudo: yes
  sudo_user: root
  gather_facts: true
  vars_files:
    - vars/db.yml
  roles:
    - { role: geerlingguy.mysql }
    - { role: geerlingguy.firewall }

- hosts: app
  sudo: yes
  sudo_user: root
  gather_facts: true
  vars_files:
    - vars/app.yml
  roles:
    - { role: geerlingguy.java }
    - { role: geerlingguy.elasticsearch }
    - { role: geerlingguy.git }
    - { role: Ken24.python }
    - { role: geerlingguy.firewall }
  tasks:
    - name: Install python dependencies
      yum: pkg={{ item }} state=present
      with_items:
        - "libtiff-devel"
        - "libjpeg-devel"
        - "libzip-devel"
        - "freetype-devel"
        - "tcl-devel"
        - "tk-devel"
        - "python-devel"
        - "mysql-devel.x86_64"

    # PDFReactor
    - name: download PDFReactor
      get_url: url=http://download.realobjects.de/PDFreactor_6_3_6828_3_unix_installer.tar.gz dest=/opt/PDFreactor_6_3_6828_3_unix_installer.tar.gz force=false
    - name: Untar PDFReactor
      unarchive: src=/opt/PDFreactor_6_3_6828_3_unix_installer.tar.gz dest=/opt copy=no
    - name: Start PDFReactor service
      command: /opt/PDFreactor/bin/pdfreactorwebservice start

    # Virtual Environment
    - name: Manually create virtual .env and install requirements  
      command: "/usr/local/bin/pip install virtualenv"
    - name: Create virtualenv
      pip: requirements=/vagrant/requirements/local.txt virtualenv=/vagrant/cfgov-refresh virtualenv_command=/usr/local/bin/virtualenv

    # Auto Source virtualenv & .env
    - name: Add environment variables to bash rc
      lineinfile: "dest=/home/vagrant/.bashrc state=present regexp='source /vagrant/cfgov-refresh/bin/activate' line='source /vagrant/cfgov-refresh/bin/activate; source /vagrant/.env'"

    # Database Syncing
    - name: Migrate django db to match application state
      shell: "source /vagrant/.env; /vagrant/cfgov-refresh/bin/python /vagrant/cfgov/manage.py migrate"



